version: "3"
services:
  postgres:
    image: "postgres:16"
    container_name: "postgres"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 30s
      retries: 100
      start_period: 30s

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  fastapi_app:
    image: "mai_app"
    
    depends_on:
      postgres:
        condition: service_healthy
        
    ports:
      - "8000:8000"

volumes:
  postgres_data: