"""empty message

Revision ID: 1cdaf48a8edd
Revises: 5f03c5db2957
Create Date: 2024-04-19 23:47:37.463111

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1cdaf48a8edd"
down_revision: Union[str, None] = "5f03c5db2957"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("bookings_event_id_fkey", "bookings", type_="foreignkey")
    op.drop_constraint("bookings_user_id_fkey", "bookings", type_="foreignkey")
    op.create_foreign_key(None, "bookings", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "bookings", "events", ["event_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "bookings", type_="foreignkey")
    op.drop_constraint(None, "bookings", type_="foreignkey")
    op.create_foreign_key(
        "bookings_user_id_fkey", "bookings", "events", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        "bookings_event_id_fkey", "bookings", "users", ["event_id"], ["id"]
    )
    # ### end Alembic commands ###
